CC=msp430-gcc
CFLAGS=-mmcu=msp430fr5969 -g -O0 -Iinclude 
LDFLAGS=-mmcu=msp430fr5969 -L. -lmementos_fram

.DUMMY: all
all: libmementos_fram.a

%.s: %.c
	$(CC) $(CFLAGS) -S -o $@ $^

%.c: include/mementos.h

libmementos_fram.a: mementos.o mementos_fram.o
	msp430-ar r $@ $^
	msp430-ranlib $@

testexe: libmementos_fram.a testexe.o
	msp430-gcc -o $@ testexe.o $(LDFLAGS)

clean:
	$(RM) libmementos_fram.a *.o testexe
