CC=msp430-gcc
CFLAGS=-mmcu=msp430fr5969 -g -Iinclude

.DUMMY: all
all: libmementos_fram.a

%.s: %.c
	$(CC) $(CFLAGS) -S -o $@ $^

%.c: include/mementos.h

libmementos_fram.a: mementos.o mementos_fram.o
	msp430-ar r $@ $^

clean:
	$(RM) libmementos_fram.a *.o
